# Generated by Django 5.0.6 on 2024-09-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0002_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_options',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='default_options',
            field=models.JSONField(default=dict),
        ),
    ]
