# Generated by Django 5.0.6 on 2024-09-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0006_customizationcategory_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
